# Generated by Django 5.2.5 on 2025-11-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
    ]
