# Generated by Django 5.2.5 on 2025-11-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
    ]
