# Generated by Django 5.2.5 on 2025-11-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Полное название вакцины')),
                ('short_name', models.CharField(help_text='Например: DHPPi+L, Нобивак Rabies', max_length=50, verbose_name='Короткое название')),
                ('for_species', models.CharField(default='Собаки и кошки', max_length=100, verbose_name='Для каких животных')),
                ('revaccination_months', models.PositiveIntegerField(default=12, verbose_name='Ревакцинация через (месяцев)')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(verbose_name='Дата прививки')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Следующая прививка')),
                ('clinic', models.CharField(blank=True, max_length=200, verbose_name='Клиника')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health.vaccine')),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
    ]
