# Generated by Django 5.2.5 on 2025-11-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('flea', 'От блох/клещей'), ('deworm', 'Дегельминтизация'), ('tick', 'От клещей отдельно'), ('complex', 'Комплексная обработка')], max_length=20, verbose_name='Тип обработки')),
                ('drug', models.CharField(max_length=200, verbose_name='Препарат')),
                ('date_given', models.DateField(verbose_name='Дата обработки')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Следующая обработка')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='pets.pet')),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата визита')),
                ('clinic', models.CharField(max_length=200, verbose_name='Клиника')),
                ('reason', models.TextField(verbose_name='Причина обращения')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('treatment', models.TextField(blank=True, verbose_name='Назначенное лечение')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость')),
                ('documents', models.FileField(blank=True, null=True, upload_to='visits/', verbose_name='Чеки/анализы')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='pets.pet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
