# Generated by Django 5.2.5 on 2025-11-25 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_treatment_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
